apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-web-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
        - name: web-app
          image: "{{ .Values.webApp.image }}"
          ports:
            - containerPort: 5000
        - name: redis
          image: "{{ .Values.redis.image }}"
          ports:
            - containerPort: 6379
